## 1) Gerekli Kütüphaneleri İçe Aktaralım

In [5]:
pip install pandas


  Using cached pandas-2.2.3-cp311-cp311-win_amd64.whl.metadata (19 kB)
  Using cached numpy-2.2.3-cp311-cp311-win_amd64.whl.metadata (60 kB)
  Using cached pytz-2025.1-py2.py3-none-any.whl.metadata (22 kB)
  Using cached tzdata-2025.1-py2.py3-none-any.whl.metadata (1.4 kB)
Using cached pandas-2.2.3-cp311-cp311-win_amd64.whl (11.6 MB)
Using cached numpy-2.2.3-cp311-cp311-win_amd64.whl (12.9 MB)
Using cached pytz-2025.1-py2.py3-none-any.whl (507 kB)
Using cached tzdata-2025.1-py2.py3-none-any.whl (346 kB)
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [6]:
import pandas as pd
import numpy as np

## 2) Aşama (a)


| Gün  | Hava Durumu | Sıcaklık | Nem   | Yağış  | Oyun |
|----- |------------|--------- |-------|--------|------|
| G1   | Güneşli    | Sıcak    | Yüksek| Seyrek | Yok  |
| G2   | Güneşli    | Sıcak    | Yüksek| Aşırı  | Yok  |
| G3   | Kapalı     | Sıcak    | Yüksek| Seyrek | Var  |
| G4   | Yağmurlu   | Ilıman   | Yüksek| Seyrek | Var  |
| G5   | Yağmurlu   | Soğuk    | Normal| Seyrek | Var  |
| G6   | Yağmurlu   | Soğuk    | Normal| Aşırı  | Yok  |
| G7   | Kapalı     | Soğuk    | Normal| Aşırı  | Var  |
| G8   | Güneşli    | Ilıman   | Yüksek| Seyrek | Yok  |
| G9   | Güneşli    | Soğuk    | Normal| Seyrek | Var  |
| G10  | Yağmurlu   | Ilıman   | Normal| Seyrek | Var  |
| G11  | Güneşli    | Ilıman   | Normal| Seyrek | Yok  |
| G12  | Kapalı     | Ilıman   | Yüksek| Aşırı  | Yok  |
| G13  | Kapalı     | Sıcak    | Normal| Seyrek | Var  |
| G14  | Yağmurlu   | Ilıman   | Yüksek| Aşırı  | Yok  |

Aşağıdaki hücrede önce DataFrame'i oluşturup `.csv` olarak kaydediyoruz, sonra da `read_csv()` ile tekrar okuyoruz.

In [7]:
# Tabloyu oluşturmak için bir sözlük (dictionary) kullanalım
data_dict = {
    'Gün': ['G1','G2','G3','G4','G5','G6','G7','G8','G9','G10','G11','G12','G13','G14'],
    'Hava Durumu': ['Güneşli','Güneşli','Kapalı','Yağmurlu','Yağmurlu','Yağmurlu','Kapalı','Güneşli','Güneşli','Yağmurlu','Güneşli','Kapalı','Kapalı','Yağmurlu'],
    'Sıcaklık': ['Sıcak','Sıcak','Sıcak','Ilıman','Soğuk','Soğuk','Soğuk','Ilıman','Soğuk','Ilıman','Ilıman','Ilıman','Sıcak','Ilıman'],
    'Nem': ['Yüksek','Yüksek','Yüksek','Yüksek','Normal','Normal','Normal','Yüksek','Normal','Normal','Normal','Yüksek','Normal','Yüksek'],
    'Yağış': ['Seyrek','Aşırı','Seyrek','Seyrek','Seyrek','Aşırı','Aşırı','Seyrek','Seyrek','Seyrek','Seyrek','Aşırı','Seyrek','Aşırı'],
    'Oyun': ['Yok','Yok','Var','Var','Var','Yok','Var','Yok','Var','Var','Yok','Yok','Var','Yok']
}

# DataFrame oluştur
df = pd.DataFrame(data_dict)

# CSV olarak kaydet
df.to_csv('tenis_verisi.csv', index=False, encoding='utf-8')

# Okuyalım
df_csv = pd.read_csv('tenis_verisi.csv', encoding='utf-8')
df_csv

Gün Hava Durumu Sıcaklık     Nem   Yağış Oyun
0    G1     Güneşli    Sıcak  Yüksek  Seyrek  Yok
1    G2     Güneşli    Sıcak  Yüksek   Aşırı  Yok
2    G3      Kapalı    Sıcak  Yüksek  Seyrek  Var
3    G4    Yağmurlu   Ilıman  Yüksek  Seyrek  Var
4    G5    Yağmurlu    Soğuk  Normal  Seyrek  Var
5    G6    Yağmurlu    Soğuk  Normal   Aşırı  Yok
6    G7      Kapalı    Soğuk  Normal   Aşırı  Var
7    G8     Güneşli   Ilıman  Yüksek  Seyrek  Yok
8    G9     Güneşli    Soğuk  Normal  Seyrek  Var
9   G10    Yağmurlu   Ilıman  Normal  Seyrek  Var
10  G11     Güneşli   Ilıman  Normal  Seyrek  Yok
11  G12      Kapalı   Ilıman  Yüksek   Aşırı  Yok
12  G13      Kapalı    Sıcak  Normal  Seyrek  Var
13  G14    Yağmurlu   Ilıman  Yüksek   Aşırı  Yok

## 3) Aşama (b)
**Pandas aracılığıyla tablodan "Sıcaklık" ve "Nem" değerlerini siliniz.**

In [8]:
# "Sıcaklık" ve "Nem" sütunlarını kaldıralım
df_dropped = df_csv.drop(columns=["Sıcaklık", "Nem"], inplace=False)
df_dropped

Gün Hava Durumu   Yağış Oyun
0    G1     Güneşli  Seyrek  Yok
1    G2     Güneşli   Aşırı  Yok
2    G3      Kapalı  Seyrek  Var
3    G4    Yağmurlu  Seyrek  Var
4    G5    Yağmurlu  Seyrek  Var
5    G6    Yağmurlu   Aşırı  Yok
6    G7      Kapalı   Aşırı  Var
7    G8     Güneşli  Seyrek  Yok
8    G9     Güneşli  Seyrek  Var
9   G10    Yağmurlu  Seyrek  Var
10  G11     Güneşli  Seyrek  Yok
11  G12      Kapalı   Aşırı  Yok
12  G13      Kapalı  Seyrek  Var
13  G14    Yağmurlu   Aşırı  Yok

## 4) Aşama (c)
**Pandas `DataFrame()` metodu ile aynı tabloyu oluşturup betimleyici istatistiksel bilgiler gösteriniz.**

Betimleyici istatistiksel bilgileri numerik olmayan (kategorik) alanlar için görmek istersek `describe(include='all')` kullanabiliriz.

In [9]:
# df zaten elimizde mevcut; isterseniz yeniden oluşturabilir veya aynı df'yi kullanabilirsiniz.
df2 = pd.DataFrame(data_dict)

# Betimleyici istatistiksel bilgiler
df2.describe(include='all')

Gün Hava Durumu Sıcaklık     Nem   Yağış Oyun
count   14          14       14      14      14   14
unique  14           3        3       2       2    2
top     G1     Güneşli   Ilıman  Yüksek  Seyrek  Yok
freq     1           5        6       7       9    7

## 5) Aşama (d)
**(3,4) boyutunda bir dizi oluşturup bu dizinin boyutunu (6,2) olacak şekilde değiştiriniz.**

In [10]:
# 3x4 boyutunda bir NumPy dizisi oluşturalım
arr = np.arange(12).reshape(3,4)
print("3x4 dizi:\n", arr, "\n")

# Boyutu 6x2 olacak şekilde yeniden şekillendirelim
arr_reshaped = arr.reshape(6,2)
print("6x2 dizi:\n", arr_reshaped)

3x4 dizi:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

6x2 dizi:
 [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


## 6) Aşama (e)
**İki tane (3,3) boyutunda rastgele sayılardan oluşan dizi oluşturun. Bu dizileri yatay ve dikey olacak şekilde istifleyin (stack).**

In [11]:
# İki adet 3x3 rastgele dizi oluşturalım (0-50 arasında örnek)
arr1 = np.random.randint(0, 50, (3,3))
arr2 = np.random.randint(0, 50, (3,3))

print("arr1:\n", arr1)
print("\narr2:\n", arr2)

# Yatay istif (hstack)
h_stacked = np.hstack((arr1, arr2))

# Dikey istif (vstack)
v_stacked = np.vstack((arr1, arr2))

print("\nYatay istif (hstack):\n", h_stacked)
print("\nDikey istif (vstack):\n", v_stacked)

arr1:
 [[39 30  7]
 [23  3 45]
 [ 6  3  8]]

arr2:
 [[20 40 38]
 [39 47 38]
 [33 49 21]]

Yatay istif (hstack):
 [[39 30  7 20 40 38]
 [23  3 45 39 47 38]
 [ 6  3  8 33 49 21]]

Dikey istif (vstack):
 [[39 30  7]
 [23  3 45]
 [ 6  3  8]
 [20 40 38]
 [39 47 38]
 [33 49 21]]
